Refactor language parameter mapping in install_from_release.sh
Azure/InnovationEngine pull request #180
Opened 2024-02-29 16:13 UTC by naioja

Refactor language parameter mapping in install_from_release.sh for all of translation we offer, including a catch all option.

2024-03-01 20:54 UTC, vmarcella commented on scripts/install_from_release.sh
> +elif [[ ${LANG_ARRAY_1[@]} =~ $MAIN_LANG_PREFIX ]]; then
Can we surround these variable accesses with quotations?

2024-03-01 21:41 UTC, mbifeld requested changes
Thanks so much for the fix Adrian!  Added a few comments

2024-03-01 21:41 UTC, mbifeld commented on scripts/install_from_release.sh
> +  fi
We need an else case here to download pt-pt incase the code is something else 'pt-xx'
```suggestion
  else
    SCENARIOS="https://github.com/MicrosoftDocs/executable-docs/releases/download/v1.0.1/pt-pt-scenarios.zip"
  fi
```

2024-03-01 21:41 UTC, mbifeld commented on scripts/install_from_release.sh
> +  SCENARIOS="https://github.com/Azure/InnovationEngine/releases/download/$RELEASE/scenarios.zip"
I feel like we could move this last else to the beginning so it runs always (and remove 19-20).  Then if any of the if statements happen it'll just overwrite SCENARIOS.
Also in the default/english case, we're not downloading scenarios from IE anymore:
```suggestion
  SCENARIOS="https://github.com/MicrosoftDocs/executable-docs/releases/download/v1.0.1/scenarios.zip"
```

2024-03-05 23:33 UTC, mbifeld approved these changes

2024-03-06 09:26 UTC, merged